scorecard/scorecard-web/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using scorecard_web.Models;
using System.Diagnostics;

namespace scorecard_web.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    public class DashboardController : Controller
    {
        /// <summary>
        /// Default method for main route
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Error page view
        /// </summary>
        /// <returns></returns>
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

scorecard/scorecard-web/Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using scorecard_web.Models;
using scorecard_web.Models.Constants;
using scorecard_web.Utils;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Net.Http;
using System.Text;
using System.Text.Json;

namespace scorecard_web.Controllers
{
    /// <summary>
    /// Controller for Search-like routes
    /// </summary>
    public class SearchController : Controller
    {
        private IConfiguration _configuration;

        public SearchController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        /// <summary>
        /// Default method for main route
        /// </summary>
        /// <returns></returns>
        [HttpGet("search")]
        public IActionResult Index()
        {
            SearchModel model = new SearchModel();
            return View(model);
        }

        /// <summary>
        /// Retrieves data from elasticsearch server with given default operator and query
        /// </summary>
        /// <param name="defaultOperator"></param>
        /// <param name="query">String with comma-separated list of key:value search terms</param>
        /// <returns></returns>
        [HttpGet("search/{defaultOperator}/{query}")]
        public IActionResult Index(string defaultOperator, string query)
        {
            List<QueryTerm> queryTerms = QueryUtils.GetQueryTerms(query);

            using (var client = new HttpClient())
            {
                query = query.Replace(CommonConstants.SEPARATOR_COMMA, CommonConstants.SEPARATOR_PLUS);

                string url = _configuration.GetSection("ElasticsearchScorecardIndexRoute").Value
                    + string.Format(CommonConstants.ROUTE_SCORECARD_SEARCH, defaultOperator, query);

                var uri = new Uri(url);

                var result = client.GetAsync(uri).GetAwaiter().GetResult();
                string data = result.Content.ReadAsStringAsync().GetAwaiter().GetResult();

                var elasticResponse = JsonConvert.DeserializeObject<ElasticSearchResponse>(data);

                List<Source> searchResults = new List<Source>();

                foreach (InnerHit hit in elasticResponse.Hits.Hits)
                {
                    searchResults.Add(hit.Source);
                }

                RegisterSearch(queryTerms);

                SearchModel model = new SearchModel(searchResults, queryTerms, defaultOperator);

                return View(model);
            }
        }

        /// <summary>
        /// Error page view
        /// </summary>
        /// <returns></returns>
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        private void RegisterSearch(List<QueryTerm> queryTerms)
        {
            using (var client = new HttpClient())
            {
                string url = _configuration.GetSection("LogstashScorecardSearchRoute").Value;

                var uri = new Uri(url);

                var content = new StringContent(
                    JsonConvert.SerializeObject(queryTerms),
                    Encoding.UTF8,
                    "application/json"
                );

                var result = client.PutAsync(uri, content).GetAwaiter().GetResult();
                string data = result.Content.ReadAsStringAsync().GetAwaiter().GetResult();
            }
        }
    }
}

scorecard/scorecard-web/Views/Shared/_DashboardPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<ul class="navbar-nav">
@if (SignInManager.IsSignedIn(User))
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
    </li>
}

scorecard/scorecard-web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Scorecard</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Scorecard</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Search" asp-action="Index">Busca</a>
                        </li>
                        <partial name="_DashboardPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - scorecard_web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>